#@TYPE: Machine
#@NAME: i.MX 8QM CPU Module with 4GB LPDDR4
#@SOC: i.MX8QM
#@DESCRIPTION: Machine configuration for Embedian i.MX 8QuadMax SMARC Module
#@MAINTAINER: Eric Lee <eric.lee@embedian.com>

MACHINEOVERRIDES =. "mx8:mx8qm:"

require conf/machine/include/imx-base.inc
require conf/machine/include/arm/armv8a/tune-cortexa72-cortexa53.inc

IMX_DEFAULT_BSP = "nxp"

MACHINE_FEATURES += "wifi bluetooth usbgadget vfat ext2 alsa serial pci nxp8997-pcie nxp9098-pcie nxpwifi-all-pcie nxpwifi-all-sdio package-management"
MACHINE_FEATURES:append:use-nxp-bsp = " optee"

# Don't include kernels in standard images
RRECOMMENDS:${KERNEL_PACKAGE_NAME}-base = ""

RDEPENDS:${KERNEL_PACKAGE_NAME}-image = ""

PREFERRED_PROVIDER_virtual/kernel:use-nxp-bsp ??= "linux-imx"

LOADADDR = ""

# We have to disable SERIAL_CONSOLE due to auto-serial-console
SERIAL_CONSOLES = "115200;ttyAMA0"

# we do not want to have getty running on tty1 as we run
# auto-serial-console there
USE_VT = "0"

KERNEL_DEVICETREE = " \
	embedian/imx8qm-smarc.dtb \
	embedian/imx8qm-smarc-lvds.dtb \
	embedian/imx8qm-smarc-hdmi.dtb \
	embedian/imx8qm-smarc-dp.dtb \
	embedian/imx8qm-smarc-rpmsg.dtb \
	embedian/imx8qm-smarc-edp.dtb \
"

PREFERRED_PROVIDER_u-boot:use-nxp-bsp = "u-boot-imx"
PREFERRED_PROVIDER_virtual/bootloader:use-nxp-bsp = "u-boot-imx"

# Set u-boot DTB
UBOOT_DTB_NAME = "imx8qm-smarc.dtb"

UBOOT_MAKE_TARGET = ""
SPL_BINARY = "spl/u-boot-spl.bin"

UBOOT_SUFFIX = "bin"

UBOOT_CONFIG_BASENAME = "smarcimx8qm"
UBOOT_CONSOLE_BASENAME = "ser3"
LPDDR4_BASENAME = "4g"
UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd]      = "${UBOOT_CONFIG_BASENAME}_${LPDDR4_BASENAME}_${UBOOT_CONSOLE_BASENAME}_defconfig,sdcard"

IMX_BOOT_SEEK = "32"

IMAGE_BOOT_FILES += "hdmitxfw.bin hdmirxfw.bin dpfw.bin"

# Set ATF platform name
ATF_PLATFORM = "imx8qm"

IMXBOOT_TARGETS = "flash_linux_m4"

IMX_BOOT_SOC_TARGET = "iMX8QM"

BOARD_TYPE = "smarc-4g"

# Add additional firmware
MACHINE_FIRMWARE:append = " linux-firmware-ath10k"

MACHINE_EXTRA_RRECOMMENDS += " \
	imx-boot \
	packagegroup-tools-bluetooth \
	pm-utils \
	kmod \
	hdparm \
	gptfdisk \
	lftp \
	vim \
	ntp \
	boost \
	nodejs \
	android-tools \
	v4l-utils \
	imx-gst1.0-plugin \
"

IMAGE_INSTALL:append = " \
	firmware-imx-sdma-imx7d \
	firmware-imx-hdmi \
	firmware-imx-xuvi-imx8 \
	sof-zephyr \
	zephyr-demo-imx \
	firmware-nxp-wifi-nxp8997-pcie \
	firmware-nxp-wifi-nxp9098-pcie \
	firmware-nxp-wifi-all-sdio \
	firmware-nxp-wifi-all-pcie \
	nxp-wlan-sdk \
	kernel-module-nxp-wlan \
	ppp \
	usb-modeswitch-data \
	usb-modeswitch \
"

IMAGE_FSTYPES = "tar.bz2"
