#@TYPE: Machine
#@NAME: EMBEDIAN i.MX6Q Plus SMARC CPU Card
#@SOC: i.MX6QP
#@DESCRIPTION: Machine configuration for Embedian i.MX6Q Plus SMARC CPU Card 2GB DDR3L
#@MAINTAINER: Eric Lee <eric.lee@embedian.com>

MACHINEOVERRIDES =. "mx6:mx6q:"

include conf/machine/include/imx6sabresd-common.inc

SERIAL_CONSOLES = "115200;ttymxc4"

MACHINE_FIRMWARE:append = " linux-firmware-ath10k"

MACHINE_FEATURES += " pci wifi bluetooth screen usbgadget vfat ext2 alsa serial usbhost nxpwifi-all-pcie"

IMAGE_FEATURES += "package-management"

PREFERRED_PROVIDER_virtual/kernel:use-nxp-bsp ??= "linux-imx"

KERNEL_DEVICETREE = " \
    embedian/imx/imx6qp-smarc.dtb \
    embedian/imx/imx6qp-smarc-wvga.dtb \
    embedian/imx/imx6qp-smarc-xga.dtb \
    embedian/imx/imx6qp-smarc-wxga.dtb \
    embedian/imx/imx6qp-smarc-1080p.dtb \
"

PREFERRED_PROVIDER_u-boot:use-nxp-bsp = "u-boot-imx"
PREFERRED_PROVIDER_virtual/bootloader:use-nxp-bsp = "u-boot-imx"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "smarcfimx6_quadplus_2g_ser3_defconfig,sdcard"

OPTEE_BIN_EXT = "6qpsmarc"

MACHINE_EXTRA_RRECOMMENDS += " \
	u-boot-imx \
	packagegroup-tools-bluetooth \
	pm-utils \
	kmod \
	hdparm \
	gptfdisk \
	lftp \
	vim \
	ntp \
	boost \
	nodejs \
	android-tools \
	v4l-utils \
	imx-gst1.0-plugin \
"

IMAGE_INSTALL:append = " \
	firmware-imx-sdma-imx7d \
	firmware-imx-sdma-imx6q \
	firmware-imx-vpu-imx6q \
	firmware-nxp-wifi-all-pcie \
	kernel-module-nxp-wlan \
	nxp-wlan-sdk \
	ppp \
	usb-modeswitch-data \
	usb-modeswitch \
"

IMAGE_FSTYPES = "tar.bz2"
