#@TYPE: Machine
#@NAME: EMBEDIAN SMARC-iMX8MP CPU Module with 4GB LPDDR4
#@SOC: i.MX8MP
#@DESCRIPTION: Machine configuration for Embedian SMARC-iMX8MP
#@MAINTAINER: Eric Lee <eric.lee@embedian.com>

MACHINEOVERRIDES =. "mx8:mx8m:mx8mp:"

require conf/machine/include/imx-base.inc
require conf/machine/include/tune-cortexa53.inc
require conf/machine/include/smarc-common.inc

MACHINE_FEATURES += " usbgadget vfat ext2 alsa serial pci wifi bluetooth optee nxp8997"

IMAGE_FEATURES += "package-management"

# Embedian BSP default providers
PREFERRED_PROVIDER_virtual/kernel_smarcimx8mp4g ?= "linux-smarcimx8mp"
PREFERRED_VERSION_linux-smarcimx8mp4g_smarcimx8mp4g = "5.10"

KERNEL_DEVICETREE = " \
                     embedian/imx8mp-smarc.dtb \
                     embedian/imx8mp-smarc-hdmi.dtb  \
                     embedian/imx8mp-smarc-lvds.dtb  \
                     embedian/imx8mp-smarc-m7.dtb \
"

WKS_FILE_DEPENDS_append = " imx-m7-demos"
IMAGE_BOOT_FILES += "imx8mp_m7_TCM_hello_world.bin \
                    imx8mp_m7_TCM_rpmsg_lite_pingpong_rtos_linux_remote.bin \
                    imx8mp_m7_TCM_rpmsg_lite_str_echo_rtos.bin \
"

PREFERRED_PROVIDER_u-boot_smarcimx8mp4g = "u-boot-smarcimx8mp"
PREFERRED_PROVIDER_virtual/bootloader_smarcimx8mp4g = "u-boot-smarcimx8mp"

UBOOT_CONFIG ??= "sd"
UBOOT_CONFIG[sd] = "smarcimx8mp_4g_ser3_defconfig,sdcard"
SPL_BINARY = "spl/u-boot-spl.bin"

# Set DDR FIRMWARE
DDR_FIRMWARE_NAME = "lpddr4_pmu_train_1d_dmem_202006.bin lpddr4_pmu_train_1d_imem_202006.bin lpddr4_pmu_train_2d_dmem_202006.bin lpddr4_pmu_train_2d_imem_202006.bin"

# Set u-boot DTB
UBOOT_DTB_NAME = "imx8mp-smarc.dtb"

# Set imx-mkimage boot target
IMXBOOT_TARGETS = "flash_evk"

# Set Serial console
SERIAL_CONSOLES = "115200;ttymxc1"

IMAGE_BOOTLOADER = "imx-boot"

LOADADDR = ""
UBOOT_SUFFIX = "bin"
UBOOT_MAKE_TARGET = ""
IMX_BOOT_SEEK = "32"

OPTEE_BIN_EXT = "8mp"

MACHINE_EXTRA_RDEPENDS += " \
			   imx-boot \
                           packagegroup-tools-bluetooth \
                           pm-utils \
                           kmod \
                           hdparm \
                           gptfdisk \
                           lftp \
                           vim \
                           ntp \
                           boost \
                           nodejs \
                           networkmanager \
			   android-tools \
                           "

# eIQ Machine Learning. Note that many of the features require Qt 5. Disable
# this when you build image without QT 5.
IMAGE_INSTALL_append = " \
	packagegroup-imx-ml \
	firmware-imx-sdma \
	firmware-imx-regulatory \
	fsl-rc-local \
        "

#TOOLCHAIN_TARGET_TASK_append += " tensorflow-lite-staticdev tensorflow-lite-dev armnn-dev onnxruntimedev"

IMAGE_FSTYPES = "tar.bz2"

# Ship all kernel modules by default
MACHINE_EXTRA_RRECOMMENDS = "kernel-modules"

# Add additional firmware
MACHINE_FIRMWARE_append = " linux-firmware-ath10k"
