# We have a conf and classes directory, append to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-smarct437x-sdk04010006"
BBFILE_PATTERN_meta-smarct437x-sdk04010006 := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-smarct437x-sdk04010006 = "20"

EMB_UBOOT_MIRROR ?= "git://git@git.embedian.com/developer/smarc-t335x-uboot.git"
EMB_KERNEL_MIRROR ?= "git://git@git.embedian.com/developer/smarc-ti-linux-kernel.git"

MIRRORS += " \
${EMB_UBOOT_MIRROR}   git://github.com/embedian/smarc-uboot.git;protocol=git;branch=${SRCBRANCH} \n \
${EMB_KERNEL_MIRROR}   git://github.com/embedian/smarc-ti-linux-kernel.git;protocol=git;branch=${SRCBRANCH} \n \
"
