PREMIRRORS_prepend = " \
	svn://.*/.* http://www.embedian.com/oe-downloads/ \n \
	git://.*/.* http://www.embedian.com/oe-downloads/ \n \
	ftp://.*/.* http://www.embedian.com/oe-downloads/ \n \
	http://.*/.* http://www.embedian.com/oe-downloads/ \n \
	https://.*/.* http://www.embedian.com/oe-downloads/ \n \
	git://source.codeaurora.org/external/imx/ git://github.com/nxp-imx/;protocol=https \n \
	https://source.codeaurora.org/external/imx/ https://github.com/nxp-imx/ \n \
	http://source.codeaurora.org/external/imx/ http://github.com/nxp-imx/ \n \
	gitsm://source.codeaurora.org/external/imx/ gitsm://github.com/nxp-imx/;protocol=https \n \
"
