PREMIRRORS_prepend = " \
     svn://.*/.* http://www.embedian.com/oe-downloads/ \n \
     git://.*/.* http://www.embedian.com/oe-downloads/ \n \
     ftp://.*/.* http://www.embedian.com/oe-downloads/ \n \
     http://.*/.* http://www.embedian.com/oe-downloads/ \n \
     https://.*/.* http://www.embedian.com/oe-downloads/ \n \"
